#!/usr/bin/env python3
import os
import subprocess
import platform
import serial.tools.list_ports

# Official Hardware IDs
UBLOX_VID = 0x1546  # u-blox AG (F9P)
ESP32_VID = 0x303a  # Espressif Systems (ESP32-S3 MCU)
SEP_VID   = 0x1513  # Septentrio (Alternative GPS)
AXIS_IP   = "192.168.42.3"

def check_host_tools():
    """Verify required host utilities are installed."""
    tools = {
        "v4l2-ctl": "v4l-utils",
        "setserial": "setserial",
        "fuser": "psmisc"
    }
    missing = []
    for tool, package in tools.items():
        if subprocess.call(["which", tool], stdout=subprocess.DEVNULL) != 0:
            missing.append(package)
    
    if missing:
        print("Warning: Missing host tools for full sanitization.")
        print(f"Please run: sudo apt update && sudo apt install -y {' '.join(missing)}")
    return len(missing) == 0

def sanitize_hardware(port):
    """The 'Sane' Reset: Kills zombies and fixes ASIO latency at the kernel level."""
    if not port or port == "virtual":
        return
    
    print(f"Sanitizing {port}...")
    try:
        # 1. Kill zombie processes
        subprocess.run(["sudo", "fuser", "-k", port], stderr=subprocess.DEVNULL)
        
        # 2. Set low latency mode
        subprocess.run(["sudo", "setserial", port, "low_latency"], stderr=subprocess.DEVNULL)
        
        # 3. Force baud and raw mode
        subprocess.run(["sudo", "stty", "-F", port, "460800", "raw", "-echo"], stderr=subprocess.DEVNULL)
        
        # 4. Ensure permissions
        subprocess.run(["sudo", "chmod", "666", port], stderr=subprocess.DEVNULL)
    except Exception as e:
        print(f"Warning during sanitization of {port}: {e}")

def scan_and_export():
    print("Scanning for Open Agbot Hardware...")
    
    check_host_tools()

    # Identify platform
    arch = platform.machine()
    is_jetson = (arch == 'aarch64')
    
    ports = serial.tools.list_ports.comports()
    
    gps_device = None
    gps_type = "none"
    mcu_device = None

    # 1. Serial Scanning (Vendor IDs)
    for port in ports:
        if port.vid == UBLOX_VID:
            gps_device = port.device
            gps_type = "ublox"
            print(f"Found u-blox GPS: {gps_device}")
        elif port.vid == SEP_VID:
            gps_device = port.device
            gps_type = "septentrio"
            print(f"Found Septentrio GPS: {gps_device}")
        elif port.vid == ESP32_VID:
            mcu_device = port.device
            print(f"Found ESP32 MCU:  {mcu_device}")

    # SBC Fallback
    if not mcu_device and is_jetson:
        mcu_device = "/dev/ttyTHS0"
        print(f"No USB MCU found. Falling back to Jetson Header: {mcu_device}")

    # 2. Camera Scanning
    usb_cam_exists = os.path.exists("/dev/video0")
    
    # Ping Axis Camera (1 second timeout)
    axis_ping = subprocess.run(
        ["ping", "-c", "1", "-W", "1", AXIS_IP], 
        stdout=subprocess.DEVNULL, 
        stderr=subprocess.DEVNULL
    ).returncode == 0

    # 3. Active Sanitization
    if gps_device:
        sanitize_hardware(gps_device)
    if mcu_device and mcu_device != "/dev/ttyTHS0":
        sanitize_hardware(mcu_device)

    # Final logic for .env
    env_gps_port = gps_device if gps_device else "virtual"
    env_mcu_port = mcu_device if mcu_device else "virtual"
    
    # Determine Status Strings
    gps_status = f"FOUND {gps_type.upper()} ({env_gps_port})" if gps_device else "GHOST"
    mcu_status = f"FOUND ({env_mcu_port})" if mcu_device else "GHOST"
    usb_status = "FOUND (/dev/video0)" if usb_cam_exists else "NOT FOUND"
    axis_status = f"ONLINE ({AXIS_IP})" if axis_ping else "OFFLINE"
    
    print(f"MCU Status: {mcu_status}")
    print(f"GPS Status: {gps_status}")
    print(f"USB Cam:    {usb_status}")
    print(f"Axis Cams:  {axis_status}")

    # 4. Write to .env
    env_path = os.path.join(os.getcwd(), ".env")
    try:
        with open(env_path, "w") as f:
            f.write("# Auto-generated by fixusb.py\n")
            f.write(f"GPS_PORT={env_gps_port}\n")
            f.write(f"GPS_TYPE={gps_type}\n")
            f.write(f"MCU_PORT={env_mcu_port}\n")
            f.write(f"USB_CAM_ENABLED={'true' if usb_cam_exists else 'false'}\n")
            f.write(f"AXIS_CAM_ENABLED={'true' if axis_ping else 'false'}\n")
            f.write(f"USER_ID={os.getuid()}\n")
            f.write(f"GROUP_ID={os.getgid()}\n")
            f.write(f"IS_JETSON={'true' if is_jetson else 'false'}\n")
        print(f"Env file updated successfully at {env_path}")
    except Exception as e:
        print(f"Failed to write .env file: {e}")

if __name__ == "__main__":
    scan_and_export()
