#!/usr/bin/env python3
"""
get_maize_topo.py — generate topo map from virtual_maize_field gt_map.csv
Usage:
  python3 get_maize_topo.py --csv <gt_map.csv> --out <path> --name <name> --rows <N>
"""
import argparse, csv, sys
from pathlib import Path
from datetime import datetime


def load_csv(path):
    crops = []
    with open(path) as f:
        for row in csv.DictReader(f):
            if row.get('kind','').strip() == 'crop':
                crops.append((float(row['X']), float(row['Y'])))
    if not crops:
        sys.exit(f"ERROR: no crop entries in {path}")
    return crops


def kmeans_1d(values, k, iterations=100):
    """1-D k-means. Returns list of k centroid values."""
    vals = sorted(values)
    # Init: evenly spaced across range
    lo, hi = vals[0], vals[-1]
    centroids = [lo + (hi - lo) * i / (k - 1) for i in range(k)]
    for _ in range(iterations):
        clusters = [[] for _ in range(k)]
        for v in vals:
            nearest = min(range(k), key=lambda i: abs(centroids[i] - v))
            clusters[nearest].append(v)
        new = []
        for i, c in enumerate(clusters):
            new.append(sum(c) / len(c) if c else centroids[i])
        if new == centroids:
            break
        centroids = new
    return sorted(centroids)


def analyse(crops, n_rows, headland):
    xs = [c[0] for c in crops]
    ys = [c[1] for c in crops]
    x_spread = max(xs) - min(xs)
    y_spread = max(ys) - min(ys)

    if y_spread >= x_spread:
        # Rows run N-S (along Y); cluster on X to find row centres
        row_centres = kmeans_1d(xs, n_rows)
        return ('NS', row_centres,
                min(ys), max(ys),
                min(ys) - headland, max(ys) + headland)
    else:
        # Rows run E-W (along X); cluster on Y
        row_centres = kmeans_1d(ys, n_rows)
        return ('EW', row_centres,
                min(xs), max(xs),
                min(xs) - headland, max(xs) + headland)


# ── YAML emission ─────────────────────────────────────────────────────────────

BT_DEFAULT = (
    r'<root main_tree_to_execute=\"MainTree\">\n'
    r'  <BehaviorTree ID=\"MainTree\">\n'
    r'    <PipelineSequence name=\"NavigateWithReplanning\">\n'
    r'      <ComputePathToPose goal=\"{goal}\" path=\"{path}\" planner_id=\"GridBased\"/>\n'
    r'      <FollowPath path=\"{path}\" controller_id=\"FollowPath\"/>\n'
    r'    </PipelineSequence>\n'
    r'  </BehaviorTree>\n'
    r'</root>\n'
)
BT_THROUGH = (
    r'<root main_tree_to_execute=\"MainTree\">\n'
    r'  <BehaviorTree ID=\"MainTree\">\n'
    r'    <PipelineSequence name=\"NavigateWithReplanning\">\n'
    r'      <ComputePathThroughPoses goals=\"{goals}\" path=\"{path}\" planner_id=\"GridBased\"/>\n'
    r'      <FollowPath path=\"{path}\" controller_id=\"FollowPath\"/>\n'
    r'    </PipelineSequence>\n'
    r'  </BehaviorTree>\n'
    r'</root>\n'
)


def header(name, date, csv_path, n_rows):
    return f"""\
# Auto-generated by get_maize_topo.py  ({date})
# Source: {csv_path}   rows: {n_rows}
meta:
  last_updated: {date}
  origin:
    latitude: 0.0
    longitude: 0.0
    altitude: 0.0
metric_map: {name}
name: {name}
pointset: {name}
transformation:
  topo_frame_id: map
  parent: map
  rotation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0
  translation:
    x: 0.0
    y: 0.0
    z: 0.0

definitions:
  default_bt: "{BT_DEFAULT}"
  goal_align_bt: "{BT_DEFAULT}"
  row_traversal_bt: "{BT_THROUGH}"

actions:
  navigate_to_pose:
    composable: false
    action_type: nav2_msgs.action.NavigateToPose
    action_server: /navigate_to_pose
    action_goal_template:
      pose:
        header:
          frame_id: ${{node.nav_frame}}
        pose: ${{node.pose}}
      behavior_tree: ${{definitions.default_bt}}
  limbic_row_follow:
    composable: false
    action_type: nav2_msgs.action.NavigateToPose
    action_server: /limbic_row_follow
    action_goal_template:
      pose:
        header:
          frame_id: ${{node.nav_frame}}
        pose: ${{node.pose}}
      behavior_tree: ''

nodes:
"""


def node(name, map_name, x, y, edges, tol_xy, tol_yaw, vert, extra=''):
    edge_lines = ''.join(
        f"    - action: {a}\n      edge_id: {eid}\n      node: {t}\n"
        for eid, t, a in edges
    )
    return f"""\
- meta:
    map: {map_name}
    node: {name}
    pointset: {map_name}
  node:
    edges:
{edge_lines}    name: {name}
    nav_frame: map
    pose:
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: {x:.3f}
        y: {y:.3f}
        z: 0.0
    properties:
      xy_goal_tolerance: {tol_xy}
      yaw_goal_tolerance: {tol_yaw}
      dropped_by: get_maize_topo
{extra}    verts:
    - x: {-vert}
      y: {-vert}
    - x: {vert}
      y: {-vert}
    - x: {vert}
      y: {vert}
    - x: {-vert}
      y: {vert}

"""


def generate(csv_path, out_path, name, n_rows, headland):
    crops = load_csv(csv_path)
    orientation, centres, c0, c1, h0, h1 = analyse(crops, n_rows, headland)
    date = datetime.now().strftime('%d-%m-%Y_%H-%M-%S')

    out = header(name, date, csv_path, n_rows)

    if orientation == 'NS':
        # Rows run N→S along Y; centres are X positions of each row
        field_cx = sum(centres) / len(centres)
        out += "# Rows run N-S (travel along Y). Entry from south.\n\n"

        out += node('HOME', name, 0.0, 0.0,
                    [('HOME_HL_S', 'HL_S', 'navigate_to_pose')],
                    0.5, 0.2, 1.5)

        hls_edges = [('HL_S_HOME','HOME','navigate_to_pose'),
                     ('HL_S_HL_N','HL_N','navigate_to_pose')]
        hls_edges += [(f'HL_S_R{i}_IN', f'R{i}_IN', 'navigate_to_pose')
                      for i in range(1, n_rows+1)]
        out += node('HL_S', name, field_cx, h0, hls_edges, 0.3, 0.1, 1.0)

        out += node('HL_N', name, field_cx, h1,
                    [('HL_N_HL_S','HL_S','navigate_to_pose')], 0.3, 0.1, 1.0)

        for i, cx in enumerate(centres, 1):
            out += f"# Row {i}  x={cx:+.3f}\n"
            out += node(f'R{i}_IN', name, cx, c0,
                        [(f'R{i}_IN_R{i}_OUT', f'R{i}_OUT', 'limbic_row_follow'),
                         (f'R{i}_IN_HL_S', 'HL_S', 'navigate_to_pose')],
                        0.1, 0.05, 0.5,
                        f"      row_id: {i}\n      row_role: entry\n")
            out += node(f'R{i}_OUT', name, cx, c1,
                        [(f'R{i}_OUT_HL_N', 'HL_N', 'navigate_to_pose')],
                        0.1, 0.05, 0.5,
                        f"      row_id: {i}\n      row_role: exit\n")

        print(f"NS map: {n_rows} rows at x={[f'{c:.2f}' for c in centres]}")
        print(f"  Y: {c0:.2f}→{c1:.2f}  HL_S={h0:.2f}  HL_N={h1:.2f}")

    else:
        # EW rows
        field_cy = sum(centres) / len(centres)
        out += "# Rows run E-W (travel along X).\n\n"

        out += node('HOME', name, 0.0, 0.0,
                    [('HOME_HL_W','HL_W','navigate_to_pose')], 0.5, 0.2, 1.5)

        hlw_edges = [('HL_W_HOME','HOME','navigate_to_pose'),
                     ('HL_W_HL_E','HL_E','navigate_to_pose')]
        hlw_edges += [(f'HL_W_R{i}_IN',f'R{i}_IN','navigate_to_pose')
                      for i in range(1, n_rows+1)]
        out += node('HL_W', name, h0, field_cy, hlw_edges, 0.3, 0.1, 1.0)
        out += node('HL_E', name, h1, field_cy,
                    [('HL_E_HL_W','HL_W','navigate_to_pose')], 0.3, 0.1, 1.0)

        for i, cy in enumerate(centres, 1):
            out += f"# Row {i}  y={cy:+.3f}\n"
            out += node(f'R{i}_IN', name, c0, cy,
                        [(f'R{i}_IN_R{i}_OUT',f'R{i}_OUT','limbic_row_follow'),
                         (f'R{i}_IN_HL_W','HL_W','navigate_to_pose')],
                        0.1, 0.05, 0.5,
                        f"      row_id: {i}\n      row_role: entry\n")
            out += node(f'R{i}_OUT', name, c1, cy,
                        [(f'R{i}_OUT_HL_E','HL_E','navigate_to_pose')],
                        0.1, 0.05, 0.5,
                        f"      row_id: {i}\n      row_role: exit\n")

        print(f"EW map: {n_rows} rows at y={[f'{c:.2f}' for c in centres]}")
        print(f"  X: {c0:.2f}→{c1:.2f}  HL_W={h0:.2f}  HL_E={h1:.2f}")

    Path(out_path).write_text(out)
    print(f"Written {out_path}")
    print(f"  export TMAP2_FILE={out_path}")


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--csv',      default='/root/.ros/virtual_maize_field/gt_map.csv')
    ap.add_argument('--out',      default='/workspace/maps/maize_map')
    ap.add_argument('--name',     default='maize_map')
    ap.add_argument('--rows',     type=int, default=6)
    ap.add_argument('--headland', type=float, default=1.5)
    args = ap.parse_args()
    generate(args.csv, args.out, args.name, args.rows, args.headland)
