"""fixusb.py must regenerate its own .env keys and leave the operator's keys alone."""

import importlib.util
import sys
import types
from pathlib import Path

import pytest


@pytest.fixture
def fixusb(monkeypatch):
    """Load fixusb.py, stubbing pyserial when it is not installed."""
    try:
        import serial.tools.list_ports
    except ImportError:
        serial = types.ModuleType('serial')
        tools = types.ModuleType('serial.tools')
        list_ports = types.ModuleType('serial.tools.list_ports')
        serial.tools, tools.list_ports = tools, list_ports
        for name, module in (('serial', serial), ('serial.tools', tools),
                             ('serial.tools.list_ports', list_ports)):
            monkeypatch.setitem(sys.modules, name, module)
    spec = importlib.util.spec_from_file_location(
        'fixusb', Path(__file__).parents[1] / 'fixusb.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


MANAGED = {'SOWBOT_SAFETY_ACK': 'true', 'MCU_PORT': '/dev/ttyACM0', 'NTRIP_ENABLED': 'false'}


def test_operator_keys_survive_and_managed_keys_are_replaced(fixusb):
    """Verify user keys, comments and order survive while managed keys are rewritten."""
    existing = (
        '# Auto-generated by fixusb.py\n'
        'SOWBOT_SAFETY_ACK=false\n'
        'MCU_PORT=virtual\n'
        'DDS_INTERFACE=eth1\n'
        '# keep the sim out of real-GPS mode\n'
        'FORCE_SIM=1\n'
        'FIELD_DATUM_LAT=51.4545\n'
    )
    result = fixusb.render_env(MANAGED, existing)
    lines = result.splitlines()
    assert lines[0] == '# Auto-generated by fixusb.py'
    assert lines.count('# Auto-generated by fixusb.py') == 1
    assert lines[1:4] == ['SOWBOT_SAFETY_ACK=true', 'MCU_PORT=/dev/ttyACM0', 'NTRIP_ENABLED=false']
    assert lines[4:] == [
        'DDS_INTERFACE=eth1', '# keep the sim out of real-GPS mode',
        'FORCE_SIM=1', 'FIELD_DATUM_LAT=51.4545',
    ]
    assert 'MCU_PORT=virtual' not in result


def test_render_is_idempotent(fixusb):
    """Verify a second run over its own output changes nothing."""
    first = fixusb.render_env(MANAGED, 'FORCE_SIM=1\n')
    assert fixusb.render_env(MANAGED, first) == first


def test_render_without_existing_file(fixusb):
    """Verify a first run on a missing .env writes only managed keys."""
    assert fixusb.render_env(MANAGED, '').splitlines()[1:] == [
        'SOWBOT_SAFETY_ACK=true', 'MCU_PORT=/dev/ttyACM0', 'NTRIP_ENABLED=false',
    ]


def test_read_env_values_ignores_comments_and_keeps_equals_in_values(fixusb):
    """Verify parsing skips comments and splits only on the first equals sign."""
    values = fixusb.read_env_values('# c\nNTRIP_ENABLED=true\nURL=a=b\n\nbad line\n')
    assert values == {'NTRIP_ENABLED': 'true', 'URL': 'a=b'}


def test_atomic_write_keeps_mode_and_leaves_no_temp_file(fixusb, tmp_path):
    """Verify replacement preserves the old file's mode and removes its temp file."""
    env = tmp_path / '.env'
    env.write_text('old\n')
    env.chmod(0o640)
    original_stat = env.stat()
    fixusb.write_env_atomically(env, 'new\n')
    assert env.read_text() == 'new\n'
    assert env.stat().st_mode & 0o777 == 0o640
    assert (env.stat().st_uid, env.stat().st_gid) == (original_stat.st_uid, original_stat.st_gid)
    assert sorted(path.name for path in tmp_path.iterdir()) == ['.env']


def test_render_replaces_all_managed_duplicates_and_preserves_operator_lines(fixusb):
    """Whitespace and duplicate settings must not resurrect stale managed values."""
    existing = (
        '  # Auto-generated by fixusb.py  \n'
        ' MCU_PORT = stale\nMCU_PORT=older\n'
        '  # operator comment with = sign\n\n'
        'DDS_INTERFACE = eth0\nDDS_INTERFACE=eth1\n'
        'CUSTOM_URL=https://example.test/?a=b=c\n'
    )
    rendered = fixusb.render_env({'MCU_PORT': 'virtual'}, existing)
    assert rendered == (
        '# Auto-generated by fixusb.py\nMCU_PORT=virtual\n'
        '  # operator comment with = sign\n\n'
        'DDS_INTERFACE = eth0\nDDS_INTERFACE=eth1\n'
        'CUSTOM_URL=https://example.test/?a=b=c\n'
    )
    assert fixusb.render_env({'MCU_PORT': 'virtual'}, rendered) == rendered


def test_read_env_values_strips_whitespace_and_last_duplicate_wins(fixusb):
    """Use the final assignment, including an explicitly empty value."""
    assert fixusb.read_env_values(
        '  # ignored=value\n =invalid\nNTRIP_ENABLED=false\n'
        ' NTRIP_ENABLED = true \nEMPTY=old\n EMPTY = \n'
    ) == {'NTRIP_ENABLED': 'true', 'EMPTY': ''}


def test_atomic_write_creates_missing_env(fixusb, tmp_path):
    """The first export creates the destination and removes its staging file."""
    env = tmp_path / '.env'
    fixusb.write_env_atomically(env, 'FORCE_SIM=1\n')
    assert env.read_text() == 'FORCE_SIM=1\n'
    assert list(tmp_path.iterdir()) == [env]


@pytest.mark.parametrize('operation', ['chown', 'chmod'])
def test_atomic_metadata_failure_preserves_original(fixusb, tmp_path, monkeypatch, operation):
    """Do not replace the operator's file if ownership or permissions cannot be kept."""
    env = tmp_path / '.env'
    env.write_text('original\n')
    env.chmod(0o600)

    def fail(*args):
        raise PermissionError('metadata denied')

    monkeypatch.setattr(fixusb.os, operation, fail)
    with pytest.raises(PermissionError, match='metadata denied'):
        fixusb.write_env_atomically(env, 'replacement\n')
    assert env.read_text() == 'original\n'
    assert env.stat().st_mode & 0o777 == 0o600
    assert list(tmp_path.iterdir()) == [env]


def test_atomic_partial_write_failure_cleans_up(fixusb, tmp_path, monkeypatch):
    """An interrupted temporary-file write must leave the destination intact."""
    env = tmp_path / '.env'
    env.write_text('original\n')

    def partial_write(path, content):
        with path.open('w') as stream:
            stream.write(content[:3])
        raise OSError('disk full')

    monkeypatch.setattr(Path, 'write_text', partial_write)
    with pytest.raises(OSError, match='disk full'):
        fixusb.write_env_atomically(env, 'replacement\n')
    assert env.read_text() == 'original\n'
    assert list(tmp_path.iterdir()) == [env]


@pytest.mark.parametrize(('process_value', 'file_value', 'expected'), [
    (None, 'true', 'true'),
    ('false', 'true', 'false'),
    ('true', 'false', 'true'),
    ('', 'true', 'true'),
    (None, '', 'false'),
    (None, None, 'false'),
])
def test_scan_export_ntrip_precedence(
    fixusb, tmp_path, monkeypatch, process_value, file_value, expected,
):
    """Exercise the real export with simulated hardware and a sudo-like environment."""
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv('NTRIP_ENABLED', raising=False)
    if process_value is not None:
        monkeypatch.setenv('NTRIP_ENABLED', process_value)
    env = tmp_path / '.env'
    if file_value is not None:
        env.write_text(f'FORCE_SIM=1\nMCU_PORT=stale\nNTRIP_ENABLED={file_value}\n')
    monkeypatch.setattr(fixusb, 'check_host_tools', lambda: True)
    monkeypatch.setattr(fixusb, 'handle_safety_disclaimer', lambda: 'true')
    monkeypatch.setattr(fixusb, 'detect_jetson', lambda: False)
    monkeypatch.setattr(fixusb.serial.tools.list_ports, 'comports', lambda: [], raising=False)
    monkeypatch.setattr(fixusb, 'sanitize_hardware', lambda *args: None)
    monkeypatch.setattr(fixusb, 'detect_camera', lambda: (str(tmp_path / 'no-camera'), 'absent'))
    monkeypatch.setattr(
        fixusb.subprocess, 'run', lambda *args, **kwargs: types.SimpleNamespace(returncode=1),
    )

    fixusb.scan_and_export()

    values = fixusb.read_env_values(env.read_text())
    assert values['NTRIP_ENABLED'] == expected
    assert values['MCU_PORT'] == 'virtual'
    assert values['SOWBOT_SAFETY_ACK'] == 'true'
    if file_value is not None:
        assert values['FORCE_SIM'] == '1'
    assert list(tmp_path.iterdir()) == [env]


def test_atomic_write_failure_leaves_original_intact(fixusb, tmp_path, monkeypatch):
    """Verify a failure before the swap keeps the original content and cleans up."""
    env = tmp_path / '.env'
    env.write_text('old\n')

    def fail(*args, **kwargs):
        raise OSError('disk full')

    monkeypatch.setattr(fixusb.os, 'replace', fail)
    with pytest.raises(OSError):
        fixusb.write_env_atomically(env, 'new\n')
    assert env.read_text() == 'old\n'
    assert sorted(path.name for path in tmp_path.iterdir()) == ['.env']
