"""fixusb.py must regenerate its own .env keys and leave the operator's keys alone."""

import importlib.util
import sys
import types
from pathlib import Path

import pytest


@pytest.fixture
def fixusb(monkeypatch):
    """Load fixusb.py, stubbing pyserial when it is not installed."""
    try:
        import serial.tools.list_ports  # noqa: F401
    except ImportError:
        serial = types.ModuleType('serial')
        tools = types.ModuleType('serial.tools')
        list_ports = types.ModuleType('serial.tools.list_ports')
        serial.tools, tools.list_ports = tools, list_ports
        for name, module in (('serial', serial), ('serial.tools', tools),
                             ('serial.tools.list_ports', list_ports)):
            monkeypatch.setitem(sys.modules, name, module)
    spec = importlib.util.spec_from_file_location(
        'fixusb', Path(__file__).parents[1] / 'fixusb.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


MANAGED = {'SOWBOT_SAFETY_ACK': 'true', 'MCU_PORT': '/dev/ttyACM0', 'NTRIP_ENABLED': 'false'}


def test_operator_keys_survive_and_managed_keys_are_replaced(fixusb):
    """Verify user keys, comments and order survive while managed keys are rewritten."""
    existing = (
        '# Auto-generated by fixusb.py\n'
        'SOWBOT_SAFETY_ACK=false\n'
        'MCU_PORT=virtual\n'
        'DDS_INTERFACE=eth1\n'
        '# keep the sim out of real-GPS mode\n'
        'FORCE_SIM=1\n'
        'FIELD_DATUM_LAT=51.4545\n'
    )
    result = fixusb.render_env(MANAGED, existing)
    lines = result.splitlines()
    assert lines[0] == '# Auto-generated by fixusb.py'
    assert lines.count('# Auto-generated by fixusb.py') == 1
    assert lines[1:4] == ['SOWBOT_SAFETY_ACK=true', 'MCU_PORT=/dev/ttyACM0', 'NTRIP_ENABLED=false']
    assert lines[4:] == [
        'DDS_INTERFACE=eth1', '# keep the sim out of real-GPS mode',
        'FORCE_SIM=1', 'FIELD_DATUM_LAT=51.4545',
    ]
    assert 'MCU_PORT=virtual' not in result


def test_render_is_idempotent(fixusb):
    """Verify a second run over its own output changes nothing."""
    first = fixusb.render_env(MANAGED, 'FORCE_SIM=1\n')
    assert fixusb.render_env(MANAGED, first) == first


def test_render_without_existing_file(fixusb):
    """Verify a first run on a missing .env writes only managed keys."""
    assert fixusb.render_env(MANAGED, '').splitlines()[1:] == [
        'SOWBOT_SAFETY_ACK=true', 'MCU_PORT=/dev/ttyACM0', 'NTRIP_ENABLED=false',
    ]


def test_read_env_values_ignores_comments_and_keeps_equals_in_values(fixusb):
    """Verify parsing skips comments and splits only on the first equals sign."""
    values = fixusb.read_env_values('# c\nNTRIP_ENABLED=true\nURL=a=b\n\nbad line\n')
    assert values == {'NTRIP_ENABLED': 'true', 'URL': 'a=b'}


def test_atomic_write_keeps_mode_and_leaves_no_temp_file(fixusb, tmp_path):
    """Verify replacement preserves the old file's mode and removes its temp file."""
    env = tmp_path / '.env'
    env.write_text('old\n')
    env.chmod(0o640)
    fixusb.write_env_atomically(env, 'new\n')
    assert env.read_text() == 'new\n'
    assert env.stat().st_mode & 0o777 == 0o640
    assert sorted(path.name for path in tmp_path.iterdir()) == ['.env']


def test_atomic_write_failure_leaves_original_intact(fixusb, tmp_path, monkeypatch):
    """Verify a failure before the swap keeps the original content and cleans up."""
    env = tmp_path / '.env'
    env.write_text('old\n')

    def fail(*args, **kwargs):
        raise OSError('disk full')

    monkeypatch.setattr(fixusb.os, 'replace', fail)
    with pytest.raises(OSError):
        fixusb.write_env_atomically(env, 'new\n')
    assert env.read_text() == 'old\n'
    assert sorted(path.name for path in tmp_path.iterdir()) == ['.env']
