name: Build Upstream Dependency Artifacts

on:
  workflow_dispatch:
  push:
    branches: [robbrit/set-up-ci]
    paths:
      - .github/workflows/build-deps.yml
      - ci/build-fields2cover.sh

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: agroecology-lab/sowbot-test

jobs:
  build-fields2cover:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ci/

      - name: Build upstream dependencies
        run: |
          sudo apt-get update
          ./ci/build-fields2cover.sh

      - name: Upload dependencies
        uses: actions/upload-artifact@v7
        with:
          name: fields2cover
          path: /tmp/Fields2Cover/dist/fields2cover.tar.gz